name: mittwotsch
description: bottus
version: 1.0.0

environment:
  sdk: '>=3.2.0'

publish_to: none

dev_dependencies:
  lints: ^4.0.0
dependencies: 
  logging: ^1.0.2
  nyxx: ^6.0.0
  modrinth_api:
    git: 
      url: https://github.com/gliscowo/modrinth_api
      ref: c1154c8
  intl: ^0.19.0
  yaml: ^3.1.1
  image: ^4.0.10
  http: ^1.1.2
  nyxx_commands: ^6.0.2
